### ISSUE TITLE
this module is logging out directly to stdout without backtrace

### ISSUE THREAD

**Issue by mmckegg** [dominictarr/multiblob#11]
Getting this every so often:

```
Error: EBADF: bad file descriptor, close
```

Managed to trace it to https://github.com/ssbc/multiblob/blob/ad02a4af58eaaf363b05aa90fd3c638c4dc99ced/index.js#L38 using devtools! 

cc @christianbundy

**Comment by dominictarr** [comment]
what is the difference between EBADF and ENOENT?

**Comment by christianbundy** [comment]
This is great, thanks! I've been wondering how to trace console output, I might have to ask you to show me that sometime.

I remember that originally I was doing `console.error(err)` and it was pretty-printing the error object without a backtrace, and when I tried `console.error(new Error(err))` it started with "Error: Error: ", but it looks like `console.error(err.toString())` isn't properly printing the stack.

I thought the difference between the two was:

- ENOENT: file does not exist at that path
- EBADF: file descriptor is somehow broken or [usually] has already been closed

Either way, a proper stacktrace would be super helpful here.

**Comment by christianbundy** [comment]
FWIW, here are the three above options:

```
# err
{ Error: EBADF: bad file descriptor, close errno: -9, code: 'EBADF', syscall: 'close' }
```

```
# err.toString()
Error: EBADF: bad file descriptor, close
```

```
# new Error(err)
Error: Error: EBADF: bad file descriptor, close
    at err (/home/christianbundy/src/ssbc/patchbay/node_modules/multiblob/index.js:45:23)
    at onNext (/home/christianbundy/src/ssbc/patchbay/node_modules/pull-catch/index.js:9:32)
    at /home/christianbundy/src/ssbc/patchbay/node_modules/multiblob/node_modules/pull-file/index.js:111:9
    at FSReqWrap.oncomplete (fs.js:135:15)
```

I think The Right Way to do this would be `new Error(err)` without the initial "Error: " prefix, but I'm not sure how to do that without some janky string replacement.

**Comment by dominictarr** [comment]
to find a trickly console.log in node, if `grep console -R node_modules` doesn't help (some times there is loads of valid logging in tests, etc) then sometimes I monkey patch console.log to include a stack trace. not sure what @mmckegg did though.

ENOENT isn't a problem, it just happens if you open a file for reading that doesn't exist. that happens when you call `multiblob.get` on a hash you don't have. this happens when trying to say, render images while offline sometimes, etc. https://github.com/ssbc/multiblob/blob/ad02a4af58eaaf363b05aa90fd3c638c4dc99ced/index.js#L38 I think just ignoring the error in that case is better.

I don't understand why EBADFD is happening though...

> Macro: int EBADF
> “Bad file descriptor.” For example, I/O on a descriptor that has been closed or reading from a descriptor open only for writing (or vice versa).

https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html
